@startuml classes_payment_adyen
set namespaceSeparator none
class "AdyenCommon" as odoo_src.odoo.addons.payment_adyen.tests.common.AdyenCommon {
  setUpClass()
}
class "AdyenController" as odoo_src.odoo.addons.payment_adyen.controllers.main.AdyenController {
  adyen_payment_details(provider_id, reference, payment_details)
  adyen_payment_methods(provider_id, formatted_amount, partner_id)
  adyen_payments(provider_id, reference, converted_amount, currency_id, partner_id, payment_method, access_token, browser_info)
  adyen_return_from_3ds_auth()
  adyen_webhook()
}
class "AdyenTest" as odoo_src.odoo.addons.payment_adyen.tests.test_adyen.AdyenTest {
  test_accept_webhook_notification_with_valid_signature()
  test_failed_webhook_authorization_notification_leaves_transaction_in_draft()
  test_failed_webhook_cancellation_notification_leaves_transaction_authorized()
  test_failed_webhook_capture_notification_leaves_transaction_authorized()
  test_failed_webhook_refund_notification_sets_refund_transaction_in_error()
  test_get_tx_from_notification_data_creates_capture_tx_when_missing()
  test_get_tx_from_notification_data_creates_refund_tx_when_missing()
  test_get_tx_from_notification_data_creates_void_tx_when_missing()
  test_get_tx_from_notification_data_returns_partial_capture_child_tx()
  test_get_tx_from_notification_data_returns_refund_tx()
  test_get_tx_from_notification_data_returns_void_tx()
  test_no_information_missing_from_partner_address()
  test_processing_values()
  test_reject_webhook_notification_with_invalid_signature()
  test_reject_webhook_notification_with_missing_signature()
  test_send_full_capture_request_does_not_create_capture_tx()
  test_send_full_void_request_does_not_create_void_tx()
  test_send_partial_capture_request_creates_capture_tx()
  test_send_partial_void_request_creates_void_tx()
  test_send_refund_request()
  test_tx_state_after_send_full_capture_request()
  test_tx_state_after_send_partial_capture_request()
  test_tx_state_after_send_void_request()
  test_webhook_notification_authorizes_transaction()
  test_webhook_notification_cancels_transaction()
  test_webhook_notification_captures_transaction()
  test_webhook_notification_confirms_transaction()
  test_webhook_notification_refunds_transaction()
  test_webhook_notification_triggers_signature_check()
}
class "PaymentCaptureWizard" as odoo_src.odoo.addons.payment_adyen.wizards.payment_capture_wizard.PaymentCaptureWizard {
  has_adyen_tx
}
class "PaymentProvider" as odoo_src.odoo.addons.payment_adyen.models.payment_provider.PaymentProvider {
  adyen_api_key
  adyen_api_url_prefix
  adyen_client_key
  adyen_hmac_key
  adyen_merchant_account
  code
  create(values_list)
  write(values)
}
class "PaymentToken" as odoo_src.odoo.addons.payment_adyen.models.payment_token.PaymentToken {
  adyen_shopper_reference
}
class "PaymentTransaction" as odoo_src.odoo.addons.payment_adyen.models.payment_transaction.PaymentTransaction {
  payment_method_id
  provider_reference
}
@enduml
