@startuml classes_l10n_ga
set namespaceSeparator none
class "AccountChartTemplate" as odoo_src.odoo.addons.l10n_ga.models.template_ga.AccountChartTemplate {
}
class "AccountChartTemplate" as odoo_src.odoo.addons.l10n_ga.models.template_ga_syscebnl.AccountChartTemplate {
}
@enduml
