@startuml classes_l10n_tg
set namespaceSeparator none
class "AccountChartTemplate" as odoo_src.odoo.addons.l10n_tg.models.template_tg.AccountChartTemplate {
}
class "AccountChartTemplate" as odoo_src.odoo.addons.l10n_tg.models.template_tg_syscebnl.AccountChartTemplate {
}
@enduml
