@startuml classes_auth_password_policy_portal
set namespaceSeparator none
class "CustomerPortalPasswordPolicy" as odoo_src.odoo.addons.auth_password_policy_portal.controllers.CustomerPortalPasswordPolicy {
}
class "IrHttp" as odoo_src.odoo.addons.auth_password_policy_portal.models.ir_http.IrHttp {
}
@enduml
