@startuml classes_mass_mailing
set namespaceSeparator none
class "IrHttp" as odoo_src.odoo.addons.mass_mailing.models.ir_http.IrHttp {
}
class "IrMailServer" as odoo_src.odoo.addons.mass_mailing.models.ir_mail_server.IrMailServer {
  active_mailing_ids
}
class "IrModel" as odoo_src.odoo.addons.mass_mailing.models.ir_model.IrModel {
  is_mailing_enabled
}
class "LinkTracker" as odoo_src.odoo.addons.mass_mailing.models.link_tracker.LinkTracker {
  mass_mailing_id
}
class "LinkTrackerClick" as odoo_src.odoo.addons.mass_mailing.models.link_tracker.LinkTrackerClick {
  mailing_trace_id
  mass_mailing_id
  add_click(code)
}
class "MailBlackList" as odoo_src.odoo.addons.mass_mailing.models.mail_blacklist.MailBlackList {
  opt_out_reason_id
}
class "MailComposeMessage" as odoo_src.odoo.addons.mass_mailing.wizard.mail_compose_message.MailComposeMessage {
  campaign_id
  mailing_list_ids
  mass_mailing_id
  mass_mailing_name
}
class "MailMail" as odoo_src.odoo.addons.mass_mailing.models.mail_mail.MailMail {
  mailing_id
  mailing_trace_ids
}
class "MailRenderMixin" as odoo_src.odoo.addons.mass_mailing.models.mail_render_mixin.MailRenderMixin {
}
class "MailThread" as odoo_src.odoo.addons.mass_mailing.models.mail_thread.MailThread {
  message_mail_with_source(source_ref)
  message_new(msg_dict, custom_values)
  message_post_with_source(source_ref)
}
class "MailingContactImport" as odoo_src.odoo.addons.mass_mailing.wizard.mailing_contact_import.MailingContactImport {
  contact_list
  mailing_list_ids
  action_import()
  action_open_base_import()
}
class "MailingContactToList" as odoo_src.odoo.addons.mass_mailing.wizard.mailing_contact_to_list.MailingContactToList {
  contact_ids
  mailing_list_id
  action_add_contacts()
  action_add_contacts_and_send_mailing()
}
class "MailingFilter" as odoo_src.odoo.addons.mass_mailing.models.mailing_filter.MailingFilter {
  create_uid
  mailing_domain
  mailing_model_id
  mailing_model_name
  name
}
class "MailingLegacy" as odoo_src.odoo.addons.mass_mailing.controllers.legacy.MailingLegacy {
  mailing_unsubscribe(mailing_id, email, res_id, token)
}
class "MailingMailingScheduleDate" as odoo_src.odoo.addons.mass_mailing.wizard.mailing_mailing_schedule_date.MailingMailingScheduleDate {
  mass_mailing_id
  schedule_date
  action_schedule_date()
}
class "MailingSubscription" as odoo_src.odoo.addons.mass_mailing.models.mailing_subscription.MailingSubscription {
  contact_id
  is_blacklisted
  list_id
  message_bounce
  opt_out
  opt_out_datetime
  opt_out_reason_id
  create(vals_list)
  open_mailing_contact()
  write(vals)
}
class "MailingSubscriptionReason" as odoo_src.odoo.addons.mass_mailing.models.mailing_subscription_optout.MailingSubscriptionReason {
  is_feedback
  name
  sequence
}
class "MailingTrace" as odoo_src.odoo.addons.mass_mailing.models.mailing_trace.MailingTrace {
  campaign_id
  email
  failure_reason
  failure_type
  links_click_datetime
  links_click_ids
  mail_mail_id
  mail_mail_id_int
  mass_mailing_id
  medium_id
  message_id
  model
  open_datetime
  reply_datetime
  res_id
  sent_datetime
  source_id
  trace_status
  trace_type
  action_view_contact()
  create(values_list)
  set_bounced(domain, bounce_message)
  set_canceled(domain)
  set_clicked(domain)
  set_failed(domain, failure_type)
  set_opened(domain)
  set_replied(domain)
  set_sent(domain)
}
class "MailingTraceReport" as odoo_src.odoo.addons.mass_mailing.report.mailing_trace_report.MailingTraceReport {
  bounced
  campaign
  canceled
  clicked
  delivered
  email_from
  error
  mailing_type
  name
  opened
  pending
  processing
  replied
  scheduled
  scheduled_date
  sent
  state
  init()
}
class "MassMailCase" as odoo_src.odoo.addons.mass_mailing.tests.common.MassMailCase {
  assertMailTraces(recipients_info, mailing, records, check_mail, sent_unlink, author, mail_links_info)
  assertMailingStatistics(mailing)
  gateway_mail_trace_bounce(mailing, record, bounce_base_values)
  gateway_mail_trace_click(mailing, record, click_label)
  gateway_mail_trace_open(mailing, record)
  gateway_mail_trace_reply(mailing, record)
}
class "MassMailCommon" as odoo_src.odoo.addons.mass_mailing.tests.common.MassMailCommon {
  setUpClass()
}
class "MassMailController" as odoo_src.odoo.addons.mass_mailing.controllers.main.MassMailController {
  full_url_redirect(code, mailing_trace_id)
  mail_blocklist_add(mailing_id, document_id, email, hash_token)
  mail_blocklist_remove(mailing_id, document_id, email, hash_token)
  mailing_confirm_unsubscribe(mailing_id, document_id, email, hash_token)
  mailing_confirm_unsubscribe_post(mailing_id, document_id, email, hash_token)
  mailing_my()
  mailing_report_deactivate(token, user_id)
  mailing_send_feedback(mailing_id, document_id, email, hash_token, last_action, opt_out_reason_id, feedback)
  mailing_unsubscribe(mailing_id, document_id, email, hash_token)
  mailing_unsubscribe_oneclick(mailing_id, document_id, email, hash_token)
  mailing_unsubscribe_placeholder_link()
  mailing_update_list_subscription(mailing_id, document_id, email, hash_token, lists_optin_ids)
  mailing_view_in_browser(mailing_id, email, document_id, hash_token)
  mailing_view_in_browser_placeholder_link()
  mass_mailing_preview_mobile_content()
  track_mail_open(mail_id, token)
}
class "MassMailing" as odoo_src.odoo.addons.mass_mailing.models.mailing.MassMailing {
  ab_testing_completed
  ab_testing_description
  ab_testing_enabled
  ab_testing_is_winner_mailing
  ab_testing_mailings_count
  ab_testing_pc
  ab_testing_schedule_datetime
  ab_testing_winner_selection
  active
  attachment_ids
  body_arch
  body_html
  bounced
  bounced_ratio
  calendar_date
  campaign_id
  canceled
  clicked
  clicks_ratio
  color
  contact_list_ids
  delivered
  email_from
  expected
  failed
  favorite
  favorite_date
  is_ab_test_sent
  is_body_empty
  keep_archives
  kpi_mail_required
  link_trackers_count
  mail_server_available
  mail_server_id
  mailing_domain
  mailing_filter_count
  mailing_filter_domain
  mailing_filter_id
  mailing_model_id
  mailing_model_name
  mailing_model_real
  mailing_on_mailing_list
  mailing_trace_ids
  mailing_type
  mailing_type_description
  medium_id
  next_departure
  next_departure_is_past
  opened
  opened_ratio
  pending
  preview
  process
  received_ratio
  replied
  replied_ratio
  reply_to
  reply_to_mode
  schedule_date
  schedule_type
  scheduled
  sent
  sent_date
  state
  subject
  total
  user_id
  warning_message
  action_cancel()
  action_compare_versions()
  action_duplicate()
  action_fetch_favorites(extra_domain)
  action_launch()
  action_put_in_queue()
  {abstract}action_reload()
  action_remove_favorite()
  action_retry_failed()
  action_schedule()
  action_select_as_winner()
  action_send_mail(res_ids)
  action_send_winner_mailing()
  action_set_favorite()
  action_test()
  action_view_bounced()
  action_view_clicked()
  action_view_delivered()
  action_view_link_trackers()
  action_view_mailing_contacts()
  action_view_opened()
  action_view_replied()
  action_view_traces_canceled()
  action_view_traces_failed()
  action_view_traces_process()
  action_view_traces_scheduled()
  action_view_traces_sent()
  convert_links()
  copy_data(default)
  create(vals_list)
  default_get(fields_list)
  write(values)
}
class "MassMailingContact" as odoo_src.odoo.addons.mass_mailing.models.mailing_contact.MassMailingContact {
  company_name
  country_id
  email
  first_name
  last_name
  list_ids
  name
  opt_out
  subscription_ids
  tag_ids
  title_id
  action_add_to_mailing_list()
  action_import()
  add_to_list(name, list_id)
  copy(default)
  create(vals_list)
  default_get(fields_list)
  fields_get(allfields, attributes)
  get_import_templates()
  name_create(name)
}
class "MassMailingList" as odoo_src.odoo.addons.mass_mailing.models.mailing_list.MassMailingList {
  active
  contact_count
  contact_count_blacklisted
  contact_count_email
  contact_count_opt_out
  contact_ids
  contact_pct_blacklisted
  contact_pct_bounce
  contact_pct_opt_out
  is_public
  mailing_count
  mailing_ids
  name
  subscription_ids
  action_merge(src_lists, archive)
  action_open_import()
  action_send_mailing()
  action_view_contacts()
  action_view_contacts_blacklisted()
  action_view_contacts_bouncing()
  action_view_contacts_email()
  action_view_contacts_opt_out()
  action_view_mailings()
  close_dialog()
  copy_data(default)
  write(vals)
}
class "MassMailingListMerge" as odoo_src.odoo.addons.mass_mailing.wizard.mailing_list_merge.MassMailingListMerge {
  archive_src_lists
  dest_list_id
  merge_options
  new_list_name
  src_list_ids
  action_mailing_lists_merge()
  default_get(fields)
}
class "Partner" as odoo_src.odoo.addons.mass_mailing.models.res_partner.Partner {
}
class "ResCompany" as odoo_src.odoo.addons.mass_mailing.models.res_company.ResCompany {
}
class "ResConfigSettings" as odoo_src.odoo.addons.mass_mailing.models.res_config_settings.ResConfigSettings {
  group_mass_mailing_campaign
  mass_mailing_mail_server_id
  mass_mailing_outgoing_mail_server
  mass_mailing_reports
  mass_mailing_split_contact_name
  show_blacklist_buttons
  get_values()
  set_values()
}
class "TestMailingABTesting" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_ab_testing.TestMailingABTesting {
  test_mailing_ab_testing_auto_flow()
  test_mailing_ab_testing_auto_flow_cron()
  test_mailing_ab_testing_campaign()
  test_mailing_ab_testing_compare()
  test_mailing_ab_testing_duplicate_date()
  test_mailing_ab_testing_manual_flow()
  test_mailing_ab_testing_minimum_participants()
}
class "TestMailingABTestingCommon" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_ab_testing.TestMailingABTestingCommon {
  ab_testing_campaign
  ab_testing_mailing_1
  ab_testing_mailing_2
  ab_testing_mailing_ids
  mailing_list
  setUp()
}
class "TestMailingContactImport" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_list.TestMailingContactImport {
  test_mailing_contact_import()
}
class "TestMailingContactToList" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_list.TestMailingContactToList {
  test_mailing_contact_to_list()
}
class "TestMailingControllers" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_controllers.TestMailingControllers {
  setUpClass()
  test_assert_initial_values()
  test_mailing_report_unsubscribe()
  test_mailing_unsubscribe_from_document_tour()
  test_mailing_unsubscribe_from_document_tour_mailing_user()
  test_mailing_unsubscribe_from_list_tour()
  test_mailing_unsubscribe_from_list_with_update_tour()
  test_mailing_unsubscribe_from_my()
  test_mailing_view()
}
class "TestMailingControllersCommon" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_controllers.TestMailingControllersCommon {
  setUpClass()
}
class "TestMailingHeaders" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_internals.TestMailingHeaders {
  setUpClass()
  test_mailing_unsubscribe_headers()
}
class "TestMailingListMerge" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_list.TestMailingListMerge {
  setUpClass()
  test_mailing_contact_create()
  test_mailing_list_action_send_mailing()
  test_mailing_list_contact_copy_in_context_of_mailing_list()
  test_mailing_list_merge()
  test_mailing_list_merge_cornercase()
}
class "TestMailingRetry" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_retry.TestMailingRetry {
  setUpClass()
  test_mailing_retry_immediate_trigger()
}
class "TestMailingScheduleDateWizard" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_mailing_schedule_date.TestMailingScheduleDateWizard {
  test_mailing_next_departure()
  test_mailing_schedule_date()
}
class "TestMailingScheduleDateWizard" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_internals.TestMailingScheduleDateWizard {
  test_mailing_schedule_date()
}
class "TestMailingTracking" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_controllers.TestMailingTracking {
  test_tracking_short_code()
  test_tracking_url_token()
}
class "TestMailingUi" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_ui.TestMailingUi {
  setUpClass()
  test_mailing_campaign_tour()
  test_mailing_editor_theme_tour()
  test_mailing_editor_tour()
  test_mass_mailing_code_view_tour()
  test_snippets_mailing_menu_tabs_tour()
  test_snippets_mailing_menu_toolbar_mobile_tour()
  test_snippets_mailing_menu_toolbar_tour()
}
class "TestMassMailFeatures" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_internals.TestMassMailFeatures {
  setUpClass()
  test_mailing_cron_trigger()
  test_mailing_deletion()
  test_mailing_on_res_partner()
  test_mailing_shortener()
}
class "TestMassMailUTM" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_internals.TestMassMailUTM {
  test_mailing_create_with_context()
  test_mailing_unique_name()
}
class "TestMassMailValues" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_internals.TestMassMailValues {
  setUpClass()
  test_mailing_body_cropped_vml_image()
  test_mailing_body_inline_image()
  test_mailing_body_responsive()
  test_mailing_computed_fields()
  test_mailing_computed_fields_default()
  test_mailing_computed_fields_default_email_from()
  test_mailing_computed_fields_domain_w_filter()
  test_mailing_computed_fields_form()
  test_mailing_editor_created_attachments()
  test_mailing_trace_values()
  test_process_mailing_queue_without_html_body()
}
class "TestMassMailing" as odoo_src.odoo.addons.mass_mailing.wizard.mailing_mailing_test.TestMassMailing {
  email_to
  mass_mailing_id
  send_mail_test()
}
class "TestMassMailingActions" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_internals.TestMassMailingActions {
  test_mailing_action_open()
}
class "TestSubscriptionManagement" as odoo_src.odoo.addons.mass_mailing.tests.test_mailing_list.TestSubscriptionManagement {
  test_mailing_update_optout()
}
class "TestUTMConsistencyMassMailing" as odoo_src.odoo.addons.mass_mailing.tests.test_utm.TestUTMConsistencyMassMailing {
  setUpClass()
  test_utm_consistency()
  test_utm_consistency_mass_mailing_user()
}
class "Users" as odoo_src.odoo.addons.mass_mailing.models.res_users.Users {
}
class "UtmCampaign" as odoo_src.odoo.addons.mass_mailing.models.utm_campaign.UtmCampaign {
  ab_testing_completed
  ab_testing_mailings_count
  ab_testing_schedule_datetime
  ab_testing_winner_mailing_id
  ab_testing_winner_selection
  bounced_ratio
  is_mailing_campaign_activated
  mailing_mail_count
  mailing_mail_ids
  opened_ratio
  received_ratio
  replied_ratio
}
class "UtmMedium" as odoo_src.odoo.addons.mass_mailing.models.utm_medium.UtmMedium {
}
class "UtmSource" as odoo_src.odoo.addons.mass_mailing.models.utm_source.UtmSource {
}
odoo_src.odoo.addons.mass_mailing.tests.common.MassMailCommon --|> odoo_src.odoo.addons.mass_mailing.tests.common.MassMailCase
odoo_src.odoo.addons.mass_mailing.tests.test_mailing_ab_testing.TestMailingABTesting --|> odoo_src.odoo.addons.mass_mailing.tests.test_mailing_ab_testing.TestMailingABTestingCommon
odoo_src.odoo.addons.mass_mailing.tests.test_mailing_controllers.TestMailingControllers --|> odoo_src.odoo.addons.mass_mailing.tests.test_mailing_controllers.TestMailingControllersCommon
odoo_src.odoo.addons.mass_mailing.tests.test_mailing_controllers.TestMailingTracking --|> odoo_src.odoo.addons.mass_mailing.tests.test_mailing_controllers.TestMailingControllersCommon
@enduml
