@startuml classes_l10n_in_purchase_stock
set namespaceSeparator none
class "AccountMove" as odoo_src.odoo.addons.l10n_in_purchase_stock.models.account_move.AccountMove {
}
class "StockMove" as odoo_src.odoo.addons.l10n_in_purchase_stock.models.stock_move.StockMove {
}
class "StockPicking" as odoo_src.odoo.addons.l10n_in_purchase_stock.models.stock_picking.StockPicking {
}
@enduml
