@startuml classes_payment_nuvei
set namespaceSeparator none
class "NuveiCommon" as odoo_src.odoo.addons.payment_nuvei.tests.common.NuveiCommon {
  setUpClass()
}
class "NuveiController" as odoo_src.odoo.addons.payment_nuvei.controllers.main.NuveiController {
  nuvei_return_from_checkout(tx_ref, error_access_token)
  nuvei_webhook()
}
class "PaymentProvider" as odoo_src.odoo.addons.payment_nuvei.models.payment_provider.PaymentProvider {
  code
  nuvei_merchant_identifier
  nuvei_secret_key
  nuvei_site_identifier
}
class "PaymentTransaction" as odoo_src.odoo.addons.payment_nuvei.models.payment_transaction.PaymentTransaction {
  payment_method_id
  provider_reference
}
class "TestPaymentProvider" as odoo_src.odoo.addons.payment_nuvei.tests.test_payment_provider.TestPaymentProvider {
  test_incompatible_with_unsupported_currencies()
  test_signature_calculation_for_incoming_data()
  test_signature_calculation_for_outgoing_data()
}
class "TestPaymentTransaction" as odoo_src.odoo.addons.payment_nuvei.tests.test_payment_transaction.TestPaymentTransaction {
  test_no_input_missing_from_redirect_form()
  test_no_item_missing_from_rendering_values()
  test_processing_notification_data_confirms_transaction()
  test_processing_notification_data_sets_transaction_in_error()
  test_processing_notification_data_sets_transaction_to_cancel()
  test_processing_notification_data_sets_unknown_transaction_in_error()
  test_processing_values_contain_rounded_amount_usd_webpay()
}
class "TestProcessingFlows" as odoo_src.odoo.addons.payment_nuvei.tests.test_processing_flows.TestProcessingFlows {
  test_accept_notification_with_valid_signature()
  test_redirect_notification_triggers_processing()
  test_redirect_notification_triggers_signature_check()
  test_reject_notification_with_invalid_signature()
  test_reject_notification_with_missing_signature()
  test_webhook_notification_triggers_processing()
  test_webhook_notification_triggers_signature_check()
}
@enduml
