@startuml classes_l10n_bf
set namespaceSeparator none
class "AccountChartTemplate" as odoo_src.odoo.addons.l10n_bf.models.template_bf.AccountChartTemplate {
}
class "AccountChartTemplate" as odoo_src.odoo.addons.l10n_bf.models.template_bf_syscebnl.AccountChartTemplate {
}
@enduml
