@startuml classes_auth_password_policy
set namespaceSeparator none
class "ResConfigSettings" as odoo_src.odoo.addons.auth_password_policy.models.res_config_settings.ResConfigSettings {
  minlength
}
class "ResUsers" as odoo_src.odoo.addons.auth_password_policy.models.res_users.ResUsers {
  get_password_policy()
}
@enduml
