@startuml classes_l10n_zm_account
set namespaceSeparator none
class "AccountChartTemplate" as odoo_src.odoo.addons.l10n_zm_account.models.template_zm.AccountChartTemplate {
}
class "AccountMove" as odoo_src.odoo.addons.l10n_zm_account.models.account_move.AccountMove {
}
@enduml
