@startuml classes_l10n_ci
set namespaceSeparator none
class "AccountChartTemplate" as odoo_src.odoo.addons.l10n_ci.models.template_ci.AccountChartTemplate {
}
class "AccountChartTemplate" as odoo_src.odoo.addons.l10n_ci.models.template_ci_syscebnl.AccountChartTemplate {
}
@enduml
