@startuml classes_account_check_printing
set namespaceSeparator none
class "AccountJournal" as odoo_src.odoo.addons.account_check_printing.models.account_journal.AccountJournal {
  bank_check_printing_layout
  check_manual_sequencing
  check_next_number
  check_sequence_id
  action_checks_to_print()
  create(vals_list)
}
class "AccountPayment" as odoo_src.odoo.addons.account_check_printing.models.account_payment.AccountPayment {
  check_amount_in_words
  check_manual_sequencing
  check_number
  payment_method_line_id
  show_check_number
  action_post()
  action_void_check()
  do_print_checks()
  fields_get(allfields, attributes)
  print_checks()
}
class "AccountPaymentMethod" as odoo_src.odoo.addons.account_check_printing.models.account_payment_method.AccountPaymentMethod {
}
class "PrintPreNumberedChecks" as odoo_src.odoo.addons.account_check_printing.wizard.print_prenumbered_checks.PrintPreNumberedChecks {
  next_check_number
  print_checks()
}
class "ResConfigSettings" as odoo_src.odoo.addons.account_check_printing.models.res_config_settings.ResConfigSettings {
  account_check_printing_date_label
  account_check_printing_layout
  account_check_printing_margin_left
  account_check_printing_margin_right
  account_check_printing_margin_top
  account_check_printing_multi_stub
}
class "TestPrintCheck" as odoo_src.odoo.addons.account_check_printing.tests.test_print_check.TestPrintCheck {
  setUpClass()
  test_check_label()
  test_draft_invoice_payment_check_printing()
  test_in_invoice_check_manual_sequencing()
  test_in_invoice_check_manual_sequencing_with_multiple_payments()
  test_multi_currency_stub_lines()
  test_multiple_payments_check_number_uniqueness()
  test_out_refund_check_manual_sequencing()
  test_print_check_with_branch()
  test_print_great_pre_number_check()
}
class "res_company" as odoo_src.odoo.addons.account_check_printing.models.res_company.res_company {
  account_check_printing_date_label
  account_check_printing_layout
  account_check_printing_margin_left
  account_check_printing_margin_right
  account_check_printing_margin_top
  account_check_printing_multi_stub
}
@enduml
