@startuml classes_hr_recruitment_skills
set namespaceSeparator none
class "CandidateSkill" as odoo_src.odoo.addons.hr_recruitment_skills.models.hr_candidate_skill.CandidateSkill {
  candidate_id
  level_progress
  skill_id
  skill_level_id
  skill_type_id
}
class "HrApplicant" as odoo_src.odoo.addons.hr_recruitment_skills.models.hr_applicant.HrApplicant {
  candidate_skill_ids
  skill_ids
}
class "HrCandidate" as odoo_src.odoo.addons.hr_recruitment_skills.models.hr_candidate.HrCandidate {
  candidate_skill_ids
  matching_score
  matching_skill_ids
  missing_skill_ids
  skill_ids
  action_create_application()
}
class "HrJob" as odoo_src.odoo.addons.hr_recruitment_skills.models.hr_job.HrJob {
  skill_ids
  action_search_matching_candidates()
}
@enduml
