@startuml classes_l10n_ro_edi_stock_batch
set namespaceSeparator none
class "L10nRoEdiStockDocument" as odoo_src.odoo.addons.l10n_ro_edi_stock_batch.models.l10n_ro_edi_stock_document.L10nRoEdiStockDocument {
  batch_id
}
class "Picking" as odoo_src.odoo.addons.l10n_ro_edi_stock_batch.models.stock_picking.Picking {
}
class "StockPickingBatch" as odoo_src.odoo.addons.l10n_ro_edi_stock_batch.models.stock_picking_batch.StockPickingBatch {
  l10n_ro_edi_stock_available_end_loc_types
  l10n_ro_edi_stock_available_operation_scopes
  l10n_ro_edi_stock_available_start_loc_types
  l10n_ro_edi_stock_document_ids
  l10n_ro_edi_stock_document_uit
  l10n_ro_edi_stock_enable
  l10n_ro_edi_stock_enable_amend
  l10n_ro_edi_stock_enable_fetch
  l10n_ro_edi_stock_enable_send
  l10n_ro_edi_stock_end_bcp
  l10n_ro_edi_stock_end_customs_office
  l10n_ro_edi_stock_end_loc_type
  l10n_ro_edi_stock_fields_readonly
  l10n_ro_edi_stock_operation_scope
  l10n_ro_edi_stock_operation_type
  l10n_ro_edi_stock_remarks
  l10n_ro_edi_stock_start_bcp
  l10n_ro_edi_stock_start_customs_office
  l10n_ro_edi_stock_start_loc_type
  l10n_ro_edi_stock_state
  l10n_ro_edi_stock_trailer_1_number
  l10n_ro_edi_stock_trailer_2_number
  l10n_ro_edi_stock_vehicle_number
  action_done()
  action_l10n_ro_edi_stock_fetch_status()
  action_l10n_ro_edi_stock_send_etransport()
}
@enduml
