@startuml classes_auth_password_policy_signup
set namespaceSeparator none
class "AddPolicyData" as odoo_src.odoo.addons.auth_password_policy_signup.controllers.AddPolicyData {
  get_auth_signup_config()
}
class "IrHttp" as odoo_src.odoo.addons.auth_password_policy_signup.models.ir_http.IrHttp {
}
@enduml
